checks:
    javascript: true

build:
    environment:
        node: v4.2.2
        mongodb: true 

    tests:
        override:
            -
                command: 'cd server && npm run coverage'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
