checks:
    javascript: true

build:
    environment:
        node: v4.2.2
        mongodb: true 

    dependencies:
        before:
            - npm install

    tests:
        override:
            -
                command: 'cd server && ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha && ./node_modules/.bin/istanbul report clover'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
