checks:
    javascript: true

build:
    environment:
        node: v4.2.2
        mongodb: true
    dependencies:
        before:
            - npm install istanbul   # or add it as part of your package.json 

    tests:
        override:
            -
                command: 'cd server && npm run coverage'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
