language: node_js
node_js:
    - "4.4"
before_install:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
    - echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    - sudo apt-get update
    - sudo apt-get install -y mongodb-org=3.2.10 mongodb-org-server=3.2.10 mongodb-org-shell=3.2.10 mongodb-org-mongos=3.2.10 mongodb-org-tools=3.2.10
    - mongo --version

services:
  - mongodb

before_script:
    - cd server/
    - npm install

script:
    - npm run coverage
    - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
