language: node_js
node_js:
    - "4.1"

services:
  - mongodb

before_script:
    - cd server/
    - npm install
    - mongo iclient_test --eval 'db.addUser("travis", "test");'

script: npm run coverage

addons:
    code_climate:
        repo_token: 9c9336ed7c9c97efd40c5096b55ae9e34aeead4065a5a351ac086ff000970a9c

after_script:
  - codeclimate-test-reporter < lcov.info
