language: node_js
node_js:
    - "4.1"

install:
  - npm install -g codecov

services:
  - mongodb

before_script:
    - cd server/
    - npm install
    - mongo iclient_test --eval 'db.addUser("travis", "test");'

script:
    - npm run coverage
    - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
