language: node_js
node_js:
    - "4.1"

services:
  - mongodb

before_script:
    - cd server/
    - npm install
    - mongo iclient_test --eval 'db.addUser("travis", "test");'

script: npm run coverage
