version: '2'
services:
    iClientMongoServer:
        image: mongo:3.2
        container_name: iClientMongoServer
        restart: always
        volumes:
         - iClientMongoData:/data/db
        ports:
         - "27017:27017"

    iClientNodeServer:
        image: node:4.6.0
        container_name: iClientNodeServer
        restart: always
        environment:
         - DATABASE_ICLIENT=${DATABASE_ICLIENT}
         - SECRET_ICLIENT=${SECRET_ICLIENT}
        command: bash -c 'cd /server/ && npm install && node /server/index.js'
        ports:
         - "3000:3000"
        volumes:
         - ./server:/server
        links:
         - iClientMongoServer
        tty: true

volumes:
    iClientMongoData:
        driver: "local"
