version: '2'
services:
    iClientNodeServer:
        image: node:4.6.0
        container_name: iClientNodeServer
        restart: always
        ports:
         - "3000:3000"
        volumes:
         - ./server:/server
        tty: true

    iClientMongoServer:
        image: mongo:3.0
        container_name: iClientMongoServer
        restart: always
        volumes:
         - iClientMongoData:/data/db
        ports:
         - "27017:27017"

volumes:
    iClientMongoData: {}
